### ISSUE TITLE
After compiling gets error

### ISSUE THREAD

**Issue by kvnbautista** [yunas/FacebookFeeds#1]
![screenshot](https://cloud.githubusercontent.com/assets/7776448/7402768/e1b34516-ee94-11e4-92b9-16dd455fcb03.png)
2015-04-29 17:26:50.824 MySocialFeeds[83064:2963485] Request failed: bad request (400)

**Comment by yunas** [comment]
This is because you have to provide your facebook app Id and app secret.
![screen shot 2015-04-30 at 13 22 30](https://cloud.githubusercontent.com/assets/213712/7409065/a6c2aa84-ef3c-11e4-9424-55fc562f0e0f.png)

**Comment by kvnbautista** [comment]
oh thank you yunas!
